[google_credentials]
type = "service_account"
project_id = "mytta2"
private_key_id = "ada0ba05d855763a38fae240d50ec57b7a096b3c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRP6M0CsV9bovn
FkoSzMMJktqI8BOMJ6X85CU5YB3Gq7LcANbsPqluA0DXNgSUcHPh0smwj4ASdSHg
9OEIOdv9VOLTigWhPavJDdk4SDI+ThG1PTWXh1e8aIkXzQI8zqwaBzM/g8IwiCwW
TFM/Ufa24cFjQyo4MjM6bf9Yh6G8EcT6v12rLJkBJl7FXivHnzofYoU97ms+ycJt
scM0zQMGRJ+JKSZG3HsGBFVs8sVYcSXIfY5+ebK6rQnNj5fqh5xCG6mxiDeBrwfK
IRcphu/ZsTW6UjkKfAK0Y5oc2HfjIdNp8E+Th2WKM107R8WOs1IzChbwMqOjsG+w
LyVP4gwPAgMBAAECggEABL+H0Xob3dXXTPg1kH4qtUCch3PefITVsEax0NMlJgsT
qPPkeSSZqIPPgtMi1mQ2sl/2dLpVykStLtifSQP0y3tGG8do5IFKze/EW7ENTQW2
uBRs90WKLYAqIYhAiN+L6lROuizPremsFBTt3VjYlj60pU7bLasc2ADwiZXySF7G
IGlzrYVkXZPwSWV04oghh/tRcAX9PrAFrQ5G2EZnpWiwNFQlHuYEJULMAwuxt0Hm
74woxMZwXlWF1aayP2TMxiDa7NoRsa6KOZTy/A2oZ7wtmXp6VBki/d/0UVhLlGCF
hIyXl7tloYmy8acIyZ+ZM3igLQ2k1RZYW4rHKKa6AQKBgQDFptewIqq4VRiJ5qTp
/UaU3pN9pAQzCTPCIckWEwFOljDo5WH/gf6niq2diW+oDhORuxHAx9VlyYQ6kpWh
kLTXZdzwRI0W5ULI1B4d+HhFvDc7aUofkFv31xH5TgRpWBTXjD9qGMNhqXkuZycx
mByY+VSTuB8aiZbvlwIjm1fIrwKBgQC8IIajttaKF3cMcQ9/KbkXkd3F0NqtbATA
NyuzCmrIP3m12V1AaCXsIsEOwSIv3YeqDpSuDkzjBwP8Wo30F/o6qg4JbMQ9OSso
YuVeBNDzpsZjjveVulUcMIQH5NZWEAJu7bCXuR4wN5s/opCDcUj0glVKtrYzsnqL
6uqIdwoKoQKBgD55VRW0b3fiVeZIw/m999BYZhBBhp5HG1gSa8gRa8lWSdFjp80m
XsLAX846wdNB18epdJwVzgrlXmlRKgCuh6rJ5MMBOANzpd9qxLY+cm3AZ0jdJ/PA
IoG9Nk4x7c0KbVQQXX8Aosk80zPqoQXZCbkEnkou2Y3+zXmfpqpwkJe7AoGAJvZB
jESAuEbV1BDSWc7FU7lVCfQQZhxZ+4kxlroQlXp39Y6X/o/TUs172FdtgiZKQ5ET
f9zcVaSNUcVbYvNYUrAHijIpjlh5tLqOsGMk92FR8yqX4j2eBOGTZqMhNN/J8Tlu
+m1PcEMD9zDu5xoeNu2LRpcCs0BCmxnDCxJEVSECgYEAhRuUh8LeFhZriCO+89A7
l7f5gT+C+wzE/q6KCzTFnj1pKxgyJEXNKnMrs2Rc3i8GHtgVzrYHMZmImXiTfHVb
rV7NfM0kIxq0mAWelPsl0Jclq5KXZsGHnYybuGhwd+UnVMF6l9vaRmR4y0uj2UEe
v0sapviJEWptnR7ocp0arVs=
-----END PRIVATE KEY-----"""
client_email = "sitesupport@mytta2.iam.gserviceaccount.com"
client_id = "104139200182560586531"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sitesupport%40mytta2.iam.gserviceaccount.com"

# ✅ 이 부분은 반드시 [google_credentials] 밖에 있어야 합니다!
default_sheet_url = "https://docs.google.com/spreadsheets/d/1cuUF2QrsUTp5pFcAM1QzoTYe6lJLVB1PJ048HuI1fOA/edit"
